version: 2.0
jobs:
 build:
   docker:
     - image: microsoft/dotnet
   working_directory: ~/neteoc
   steps:
     - checkout
     - run: dotnet publish
     - run: ls bin/release/publish 
     - run: ssh neteoc:${netEocPass}@${boxIP} && echo $HOSTNAME
