version: 2.0
jobs:
 build:
   docker:
     - image: microsoft/dotnet
   working_directory: ~/neteoc
   steps:
     - run: apt update && apt upgrade -y
     - run: apt-get install -y sshpass
     - checkout
     - run: cd Source && dotnet restore && dotnet publish
     - run: echo ${boxIP}
     - run: sshpass -p "${netEocPass}" scp -r Source/Services/NetEOC.Auth/bin/Debug/netcoreapp1.0/publish neteoc@${boxIP}:/home/ubuntu/delme/
