version: 2.0
jobs:
 build:
   docker:
     - image: microsoft/dotnet
   working_directory: ~/neteoc
   steps:
     - checkout
     - run: cd Source
     - run: dotnet restore
     - run: dotnet publish
     - run: ls Source/bin/Release/PublishOutput 
     - run: ssh neteoc:${netEocPass}@${boxIP} && echo $HOSTNAME
